// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1._1.DAL;

namespace _1._1.Migrations
{
    [DbContext(typeof(PersonalCustomerCardsContext))]
    [Migration("20211212125331_CreatePersonalCustomerCards")]
    partial class CreatePersonalCustomerCards
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_1._1.DAL.Model.PersonalCard", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<float>("Discount")
                        .HasColumnType("real")
                        .HasColumnName("discount");

                    b.HasKey("Id");

                    b.ToTable("personal_card");
                });

            modelBuilder.Entity("_1._1.DAL.Model.Purchase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CarId")
                        .HasColumnType("bigint")
                        .HasColumnName("card_id");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("purchase_sum");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("purchase");
                });

            modelBuilder.Entity("_1._1.DAL.Model.UserProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("date")
                        .HasColumnName("birthdate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.HasKey("Id");

                    b.ToTable("user_profile");
                });

            modelBuilder.Entity("_1._1.DAL.Model.PersonalCard", b =>
                {
                    b.HasOne("_1._1.DAL.Model.UserProfile", "User")
                        .WithOne("PersonalCard")
                        .HasForeignKey("_1._1.DAL.Model.PersonalCard", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("_1._1.DAL.Model.Purchase", b =>
                {
                    b.HasOne("_1._1.DAL.Model.PersonalCard", "Card")
                        .WithMany("Purchases")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("_1._1.DAL.Model.PersonalCard", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("_1._1.DAL.Model.UserProfile", b =>
                {
                    b.Navigation("PersonalCard");
                });
#pragma warning restore 612, 618
        }
    }
}
